### PR TITLE
Use `cmath` for `Math` on both Windows and Linux

### LINKED ISSUE #50: Why use different header files for Windows versus Linux?
https://github.com/Open-Systems-Pharmacology/OSPSuite.FuncParser/blob/master/src/OSPSuite.FuncParserNative/src/Math.cpp

This is probably my ignorance on display, but I am genuinely curious.

For example, why do this?

```cpp
#ifdef linux
#include <cmath>
#endif

double Math::GetNaN ()
{
#ifdef _WINDOWS
	return _Nan._Double;
#endif
#ifdef linux 
	return NAN;
#endif
}
```

And not this?

```cpp
#include <cmath>

double Math::GetNaN ()
{
	return NAN;
}
```

I've used `<cmath>` successfully on Windows.

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Closes #50

### CODE REVIEW

**Review by msevestre — CHANGES_REQUESTED** [review]
Please add tests

**Comment by IndrajeetPatil** [comment]
I will mark this "Ready for review" when I manage to add tests. Need to figure how to do it first 😅

**Comment by IndrajeetPatil** [comment]
I thought this covered the code in question, but probably not:

https://github.com/Open-Systems-Pharmacology/OSPSuite.FuncParser/blob/532b6d8cc52f67dccefbc794dd7175f62d86c099/tests/TestFuncParserCPP/TestFuncParser.cpp#L60-L70

**Comment by Yuri05** [comment]
>I thought this covered the code in question, but probably not:

No, this is just a small command line app for interactive tests and e.g. for memory/performance profilers etc.
It is neither compiled nor executed on AppVeyor.

As @msevestre said (s. https://github.com/Open-Systems-Pharmacology/OSPSuite.FuncParser/issues/50#issuecomment-1084961036) all tests are part of **OSPSuite.FuncParser.Tests** project, which is included into the "main solution **OSPSuite.FuncParser.sln**
If you open the solution in Visual Studio, you can run all the tests either via Resharper or via VS built-in test runner

**Comment by IndrajeetPatil** [comment]
Closing this as I won't be able to add any tests.

**Pull request closed without merging**
